backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

# media
media_folder: "themes/schmopera/static/images"
public_folder: "images"


# collections
collections:
# Articles
- name: 'articles'
  label: 'Articles'
  folder: 'content/articles'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { label: "Title of article", name: "title", widget: "string" }
  - { label: "Slug", name: "slug", widget: "string" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Author(s)", name: "author", widget: "list", allow_add: true, collapsed: true, field: {label: Author File, name: file, widget: string} }
  - { label: "Category", name: "categories", widget: "select", options: ["Editorial", "How-To", "Humour", "Interview", "Meta", "Op-Ed", "Review"] }
  - { label: "Primary Image", name: "primary_image", widget: "image", choose_url: true }
  - { label: "Primary Image Credit", name: "primary_image_credit", widget: "markdown", minimal: true }
  - { label: "Short Description", name: "short_description", widget: "markdown", minimal: true }
  - { label: "Disclaimer", name: "disclaimer", widget: "string" }
  - { label: "Preamble", name: "preamble", widget: "markdown", minimal: true }
  - { label: "Postamble", name: "postamble", widget: "markdown", minimal: true }
  - { label: "Youtube URL", name: "youtube_url", widget: "string" }
  - { label: "Related Articles", name: "related_articles", widget: "list", add_to_top: true, allow_add: true, collapsed: true, field: {label: Article File, name: file, widget: string} }
  - { label: "People", name: "related_people", widget: "list", add_to_top: true, allow_add: true, collapsed: true, field: {label: People File, name: file, widget: string} }
  - { label: "Companies", name: "related_companies", widget: "list", add_to_top: true, allow_add: true, collapsed: true, field: {label: Company File, name: file, widget: string} }
  - { label: "Content", name: "body", widget: "markdown" }


# Featured Articles
- name: "featured_articles"
  label: "Featured Articles"
  folder: "content/featured"
  editor:
     preview: false
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { widget: "string", name: "title", label: "Title" }
  - { widget: "string", name: "type", label: "Type" }
  - { widget: "string", name: "url", label: "URL" }
  - { widget: "list", name: "articles", label: "Featured Article List", add_to_top: true, field: {label: Article File, name: file, widget: string} }


# Authors
- name: 'authors'
  label: 'Authors'
  folder: 'content/authors'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Slug", name: "slug", widget: "string" }
  - { label: "Primary Image", name: "primary_image", widget: "image" }
  - { label: "Short bio", name: "short_bio", widget: "markdown", minimal: true }
  - { label: "Email Address", name: "email", widget: "string" }
  - { label: "Website", name: "website", widget: "string" }
  - label: Social Media
    name: social_media
    widget: list
    fields:
    - { label: "Platform", name: "platform", widget: "select", options: ["Facebook", "Twitter", "Instagram", "Youtube", "Linkedin", "Soundcloud"] }
    - { label: "Template", name: "template", widget: "string", default: "social-media" }
    - { label: "URL", name: "url", widget: "string" }
  - { label: "Content", name: "body", widget: "markdown" }

  
# About
- name: "about"
  label: "About"
  folder: "content/about"
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { widget: "string", name: "title", label: "Title" }
  - { widget: "markdown", name: "body", label: "Content" }


# Scene's Companies & People
- name: "scene"
  label: "Scene"
  editor:
     preview: false
  files:
    - label: "Company Page"
      name: "company"
      file: "content/scene/companies/_index.md"
      fields:
      - { label: Title, name: title, widget: string }
      - { label: Type, name: type, widget: string }
      - { label: URL, name: url, widget: string }
    - label: "People Page"
      name: "people"
      file: "content/scene/people/_index.md"
      fields:
      - { label: Title, name: title, widget: string }
      - { label: Type, name: type, widget: string }
      - { label: URL, name: url, widget: string }


# Companies
- name: 'companies'
  label: 'Companies'
  folder: 'content/scene/companies'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  filter: {field: "cms_visible", value: true}
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { widget: "string", name: "title", label: "Title" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Last Mod", name: "lastmod", widget: "datetime" }
  - { widget: "string", name: "slug", label: "Slug" }
  - { widget: "image", name: "primary_image", label: "Primary Image", choose_url: true }
  - { name: "primary_image_credit", label: "Primary Image Credit", widget: "markdown", minimal: true }
  - { widget: "string", name: "type_of_company", label: "Type of Company" }
  - { widget: "string", name: "website", label: "Website" }
  - { widget: "markdown", name: "address", label: "Address", minimal: true }
  - { widget: "string", name: "email", label: "Contact Email" }
  - label: Social Media
    name: social_media
    widget: list
    fields:
    - { label: "Platform", name: "platform", widget: "select", options: ["Facebook", "Twitter", "Instagram", "Youtube", "Linkedin", "Soundcloud"] }
    - { label: "Template", name: "template", widget: "string", default: "social-media" }
    - { label: "URL", name: "url", widget: "string" }
  - { label: "Related People", name: "related_people", widget: "list", add_to_top: true, allow_add: true, collapsed: true, field: {label: People File, name: file, widget: string} }
  - { label: "Content", name: "body", widget: "markdown" }


# People
- name: 'people'
  label: 'People'
  folder: 'content/scene/people'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  filter: {field: "cms_visible", value: true}
  fields:
  - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - { widget: "string", name: "title", label: "Title" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Last Mod", name: "lastmod", widget: "datetime" }
  - { widget: "string", name: "slug", label: "Slug" }
  - { widget: "image", name: "primary_image", label: "Primary Image", choose_url: true }
  - { name: "primary_image_credit", label: "Primary Image Credit", widget: "markdown", minimal: true }
  - { widget: "string", name: "type_of_company", label: "Type of Company" }
  - { widget: "string", name: "website", label: "Website" }
  - { widget: "markdown", name: "address", label: "Address", minimal: true }
  - { widget: "string", name: "email", label: "Contact Email" }
  - label: Social Media
    name: social_media
    widget: list
    fields:
    - { label: "Platform", name: "platform", widget: "select", options: ["Facebook", "Twitter", "Instagram", "Youtube", "Linkedin", "Soundcloud"] }
    - { label: "Template", name: "template", widget: "string", default: "social-media" }
    - { label: "URL", name: "url", widget: "string" }
  - { label: "Related Companies", name: "related_companies", widget: "list", add_to_top: true, allow_add: true, collapsed: true, field: {label: Company File, name: file, widget: string} }
  - { label: "Content", name: "body", widget: "markdown" }