backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# media
media_folder: "themes/schmopera/static/images"
public_folder: "images"


# collections
collections:
# Articles
- name: 'articles'
  label: 'Articles'
  folder: 'content/articles'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
  - { label: "Title of article", name: "title", widget: "string" }
  - { label: "Slug", name: "slug", widget: "string" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Author(s)", name: "author", widget: "list", allow_add: true, collapsed: true, field: {label: Author File, name: file, widget: string} }
  - { label: "Category", name: "categories", widget: "select", options: ["Editorial", "How-To", "Humour", "Interview", "Meta", "Op-Ed", "Review"] }
  - { label: "Primary Image", name: "primary_image", widget: "image", choose_url: true }
  - { label: "Primary Image Credit", name: "primary_image_credit", widget: "markdown", minimal: true }
  - { label: "Short Description", name: "short_description", widget: "markdown", minimal: true }
  - { label: "Disclaimer", name: "disclaimer", widget: "string" }
  - { label: "Preamble", name: "preamble", widget: "markdown", minimal: true }
  - { label: "Postamble", name: "postamble", widget: "markdown", minimal: true }
  - { label: "Youtube URL", name: "youtube_url", widget: "string" }
  - { label: "Related Articles", name: "related_articles", widget: "list", allow_add: true, collapsed: true, field: {label: Article File, name: file, widget: string} }
  - { label: "People", name: "related_people", widget: "list", allow_add: true, collapsed: true, field: {label: People File, name: file, widget: string} }
  - { label: "Companies", name: "related_companies", widget: "list", allow_add: true, collapsed: true, field: {label: Company File, name: file, widget: string} }
  - { label: "Content", name: "body", widget: "markdown" }


# Featured Articles
- label: "Featured Articles"
  name: "featured_articles"
  path: "content/featured"
  fields:
  - { widget: "string", name: "title", label: "Title" }
  - { widget: "string", name: "type", label: "Type" }
  - { widget: "string", name: "url", label: "URL" }
  - { widget: "string", name: "articles", label: "Featured Article List", list: true, allow_add: true, collapsed: true, field: {label: Article File, name: file, widget: string} }


# Authors
- name: 'authors'
  label: 'Authors'
  folder: 'content/authors'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Slug", name: "slug", widget: "string" }
  - { label: "Primary Image", name: "primary_image", widget: "image" }
  - { label: "Short bio", name: "short_bio", widget: "markdown", minimal: true }
  - { label: "Email Address", name: "email", widget: "string" }
  - { label: "Website", name: "website", widget: "string" }
  - label: Social Media
    name: social_media
    widget: list
    fields:
    - { label: "Platform", name: "platform", widget: "string" }
    - { label: "Template", name: "template", widget: "string", default: "social-media" }
    - { label: "URL", name: "url", widget: "string" }
  - { label: "Content", name: "body", widget: "markdown" }

  
# About
- label: "About"
  name: "about"
  path: "content/about"
  fields:
  - { widget: "string", name: "title", label: "Title" }
  - { widget: "markdown", name: "body", label: "Content" }